// <auto-generated />
using System;
using EShopApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EShopApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EShopApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Bilgisayar",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yüksek performanslı laptop",
                            IsDeleted = false,
                            Name = "Laptop Pro",
                            Price = 1299.99m,
                            RowVersion = new byte[0],
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "Bilgisayar",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oyuncular için gelişmiş laptop",
                            IsDeleted = false,
                            Name = "Gaming Laptop",
                            Price = 1599.99m,
                            RowVersion = new byte[0],
                            Stock = 7
                        },
                        new
                        {
                            Id = 3,
                            Category = "Bilgisayar",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Taşınabilir ve hafif ultrabook",
                            IsDeleted = false,
                            Name = "Ultrabook",
                            Price = 999.99m,
                            RowVersion = new byte[0],
                            Stock = 12
                        },
                        new
                        {
                            Id = 4,
                            Category = "Telefon",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Amiral gemisi akıllı telefon",
                            IsDeleted = false,
                            Name = "Smartphone X",
                            Price = 899.99m,
                            RowVersion = new byte[0],
                            Stock = 5
                        },
                        new
                        {
                            Id = 5,
                            Category = "Telefon",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uygun fiyatlı akıllı telefon",
                            IsDeleted = false,
                            Name = "Smartphone Lite",
                            Price = 499.99m,
                            RowVersion = new byte[0],
                            Stock = 9
                        },
                        new
                        {
                            Id = 6,
                            Category = "Bilgisayar Ürünleri",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "RGB mekanik klavye",
                            IsDeleted = false,
                            Name = "Mechanical Keyboard",
                            Price = 129.99m,
                            RowVersion = new byte[0],
                            Stock = 20
                        },
                        new
                        {
                            Id = 7,
                            Category = "Bilgisayar Ürünleri",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yüksek hassasiyetli oyuncu faresi",
                            IsDeleted = false,
                            Name = "Gaming Mouse",
                            Price = 59.99m,
                            RowVersion = new byte[0],
                            Stock = 30
                        },
                        new
                        {
                            Id = 8,
                            Category = "Bilgisayar Ürünleri",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "27 inç 4K monitör",
                            IsDeleted = false,
                            Name = "4K Monitor",
                            Price = 349.99m,
                            RowVersion = new byte[0],
                            Stock = 8
                        },
                        new
                        {
                            Id = 9,
                            Category = "Bilgisayar Ürünleri",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1080p çözünürlüklü webcam",
                            IsDeleted = false,
                            Name = "Webcam HD",
                            Price = 49.99m,
                            RowVersion = new byte[0],
                            Stock = 15
                        },
                        new
                        {
                            Id = 10,
                            Category = "Bilgisayar Ürünleri",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Çok amaçlı bağlantı istasyonu",
                            IsDeleted = false,
                            Name = "USB-C Dock",
                            Price = 79.99m,
                            RowVersion = new byte[0],
                            Stock = 14
                        },
                        new
                        {
                            Id = 11,
                            Category = "Bilgisayar Ürünleri",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1TB hızlı taşınabilir SSD",
                            IsDeleted = false,
                            Name = "External SSD",
                            Price = 149.99m,
                            RowVersion = new byte[0],
                            Stock = 10
                        },
                        new
                        {
                            Id = 12,
                            Category = "Bilgisayar Ürünleri",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DDR4 3200MHz RAM",
                            IsDeleted = false,
                            Name = "RAM 16GB",
                            Price = 69.99m,
                            RowVersion = new byte[0],
                            Stock = 18
                        },
                        new
                        {
                            Id = 13,
                            Category = "Bilgisayar Ürünleri",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sessiz işlemci soğutucusu",
                            IsDeleted = false,
                            Name = "CPU Cooler",
                            Price = 39.99m,
                            RowVersion = new byte[0],
                            Stock = 13
                        },
                        new
                        {
                            Id = 14,
                            Category = "Bilgisayar Ürünleri",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "650W 80+ Bronze güç kaynağı",
                            IsDeleted = false,
                            Name = "Power Supply 650W",
                            Price = 89.99m,
                            RowVersion = new byte[0],
                            Stock = 9
                        },
                        new
                        {
                            Id = 15,
                            Category = "Bilgisayar Ürünleri",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ATX oyuncu kasası",
                            IsDeleted = false,
                            Name = "PC Case",
                            Price = 99.99m,
                            RowVersion = new byte[0],
                            Stock = 6
                        },
                        new
                        {
                            Id = 16,
                            Category = "Aksesuar",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Taşınabilir bluetooth hoparlör",
                            IsDeleted = false,
                            Name = "Bluetooth Speaker",
                            Price = 39.99m,
                            RowVersion = new byte[0],
                            Stock = 25
                        },
                        new
                        {
                            Id = 17,
                            Category = "Aksesuar",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yüksek kapasiteli powerbank",
                            IsDeleted = false,
                            Name = "Powerbank 20.000mAh",
                            Price = 29.99m,
                            RowVersion = new byte[0],
                            Stock = 30
                        },
                        new
                        {
                            Id = 18,
                            Category = "Aksesuar",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hızlı şarj kablosu",
                            IsDeleted = false,
                            Name = "Charging Cable",
                            Price = 9.99m,
                            RowVersion = new byte[0],
                            Stock = 50
                        },
                        new
                        {
                            Id = 19,
                            Category = "Aksesuar",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kablosuz hızlı şarj cihazı",
                            IsDeleted = false,
                            Name = "Wireless Charger",
                            Price = 24.99m,
                            RowVersion = new byte[0],
                            Stock = 22
                        },
                        new
                        {
                            Id = 20,
                            Category = "Aksesuar",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ayarlanabilir telefon standı",
                            IsDeleted = false,
                            Name = "Phone Stand",
                            Price = 14.99m,
                            RowVersion = new byte[0],
                            Stock = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
