# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# csproj dosyasını kopyala ve bağımlılıkları yükle
COPY *.csproj ./
RUN dotnet restore

# Diğer dosyaları kopyala ve derle(build yap)
COPY . ./
RUN dotnet build -c Release -o /app/build

# Publish stage
FROM build AS publish
RUN dotnet publish -c Release -o /app/publish

# Runtime Stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

# Published dosyaları publish stageden runtime stage kopyala
COPY --from=publish /app/publish .

# port
EXPOSE 8080

# Environment Variables
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Production

# Uygulamayı çalıştır
ENTRYPOINT [ "dotnet", "EShopApp.dll" ]



